Class {
	#name : #SIYAlgae,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 17:34'
}
SIYAlgae >> blockTexture [

	^ '/SIYAlgae.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 17:34'
}
SIYAlgae >> nounTexture [

	^ '/SIYAlgaeT.png' 
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/4/2024 15:08'
}
SIYAlgae >> symbol [

	^ #algae
]
