Class {
	#name : #SIYBubble,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 19:44'
}
SIYBubble >> blockTexture [

	^ '/SIYBubble.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 19:44'
}
SIYBubble >> nounTexture [

	^ '/SIYBubbleT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/4/2024 15:08'
}
SIYBubble >> symbol [

	^ #bubble
]
