Class {
	#name : #SIYBrick,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 19:06'
}
SIYBrick >> blockTexture [

	^ '/SIYBrick.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 19:06'
}
SIYBrick >> nounTexture [

	^ '/SIYBrickT.png' 
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/4/2024 15:08'
}
SIYBrick >> symbol [

	^ #brick
]
