Class {
	#name : #SIYCrab,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 17:35'
}
SIYCrab >> blockTexture [

	^ '/SIYCrab.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 17:47'
}
SIYCrab >> nounTexture [

	^ '/SIYCrabT.png' 
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:29'
}
SIYCrab >> symbol [

	^ #crab
]
