Class {
	#name : #SIYCog,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/15/2024 22:41'
}
SIYCog >> blockTexture [

	^ '/SIYCog.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/15/2024 22:41'
}
SIYCog >> nounTexture [

	^ '/SIYCogT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/4/2024 15:08'
}
SIYCog >> symbol [

	^ #cog
]
