Class {
	#name : #SIYDoor,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'KD 1/4/2024 16:54'
}
SIYDoor >> blockTexture [

	^ '/SIYDoor.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'KD 1/4/2024 16:55'
}
SIYDoor >> nounTexture [

	^ '/SIYDoorT.png' 
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:29'
}
SIYDoor >> symbol [

	^ #door
]
