Class {
	#name : #SIYFlag,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 12:54'
}
SIYFlag >> blockTexture [

	^ '/SIYFlag.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 12:56'
}
SIYFlag >> nounTexture [

	^ '/SIYFlagT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/4/2024 15:08'
}
SIYFlag >> symbol [

	^ #flag
]
