Class {
	#name : #SIYFlag,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 12:54'
}
SIYFlag >> blockTexture [

	^ '/SIYFlag.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 12:56'
}
SIYFlag >> nounTexture [

	^ '/SIYFlagT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:30'
}
SIYFlag >> symbol [

	^ #flag
]
