Class {
	#name : #SIYFlower,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/5/2024 15:49'
}
SIYFlower >> blockTexture [

	^ '/SIYFlower.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/5/2024 15:49'
}
SIYFlower >> nounTexture [

	^ '/SIYFlowerT.png' 
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:30'
}
SIYFlower >> symbol [

	^ #flower
]
