Class {
	#name : #SIYGrass,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'KD 1/4/2024 18:32'
}
SIYGrass >> blockTexture [

	^ '/SIYGrass.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'KD 1/4/2024 18:32'
}
SIYGrass >> nounTexture [

	^ '/SIYGrassT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:30'
}
SIYGrass >> symbol [

	^ #grass
]
