Class {
	#name : #SIYHedge,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 22:01'
}
SIYHedge >> blockTexture [

	^ '/SIYHedge.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 22:01'
}
SIYHedge >> nounTexture [

	^ '/SIYHedgeT.png' 
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:30'
}
SIYHedge >> symbol [

	^ #hedge
]
