Class {
	#name : #SIYIce,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/5/2024 23:12'
}
SIYIce >> blockTexture [

	^ '/SIYIce.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/5/2024 23:12'
}
SIYIce >> nounTexture [

	^ '/SIYIceT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:30'
}
SIYIce >> symbol [

	^ #ice
]
