Class {
	#name : #SIYJelly,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/5/2024 23:12'
}
SIYJelly >> blockTexture [

	^ '/SIYJelly.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/5/2024 23:12'
}
SIYJelly >> nounTexture [

	^ '/SIYJellyT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/4/2024 15:08'
}
SIYJelly >> symbol [

	^ #jelly
]
