Class {
	#name : #SIYKey,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'KD 1/4/2024 16:57'
}
SIYKey >> blockTexture [

	^ '/SIYKey.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'KD 1/4/2024 16:57'
}
SIYKey >> nounTexture [

	^ '/SIYKeyT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/4/2024 15:08'
}
SIYKey >> symbol [

	^ #key
]
