Class {
	#name : #SIYLava,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 12:54'
}
SIYLava >> blockTexture [

	^ '/SIYLava.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 12:56'
}
SIYLava >> nounTexture [

	^ '/SIYLavaT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/4/2024 15:08'
}
SIYLava >> symbol [

	^ #lava
]
