Class {
	#name : #SIYPillar,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 19:06'
}
SIYPillar >> blockTexture [

	^ '/SIYPillar.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 19:06'
}
SIYPillar >> nounTexture [

	^ '/SIYPillarT.png' 
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:30'
}
SIYPillar >> symbol [

	^ #pillar
]
