Class {
	#name : #SIYSqueak,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/5/2024 16:46'
}
SIYSqueak >> blockTexture [

	^ self blockTextureDown
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 16:53'
}
SIYSqueak >> blockTextureDown [

	^ '/SIYSqueak-FacingDown.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 16:53'
}
SIYSqueak >> blockTextureLeft [

	^ '/SIYSqueak-FacingLeft.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 16:53'
}
SIYSqueak >> blockTextureRight [

	^ '/SIYSqueak-FacingRight.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 16:53'
}
SIYSqueak >> blockTextureUp [

	^ '/SIYSqueak-FacingUp.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 12:57'
}
SIYSqueak >> nounTexture [

	^ '/SIYSqueakT.png'
]
