Class {
	#name : #SIYStar,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 17:35'
}
SIYStar >> blockTexture [

	^ '/SIYStar.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/6/2024 17:51'
}
SIYStar >> nounTexture [

	^ '/SIYStarT.png' 
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:30'
}
SIYStar >> symbol [

	^ #star
]
