Class {
	#name : #SIYSkull,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'KD 1/4/2024 18:34'
}
SIYSkull >> blockTexture [

	^ '/SIYSkull.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'KD 1/4/2024 18:34'
}
SIYSkull >> nounTexture [

	^ '/SIYSkullT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:30'
}
SIYSkull >> symbol [

	^ #skull
]
