Class {
	#name : #SIYTile,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/5/2024 21:08'
}
SIYTile >> blockTexture [

	^ '/SIYTile.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/5/2024 21:08'
}
SIYTile >> nounTexture [

	^ '/SIYTileT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/3/2024 20:31'
}
SIYTile >> symbol [

	^ #tile
]
