Class {
	#name : #SIYWall,
	#superclass : #SIYBlock,
	#category : #'SIY-Blocks'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 12:54'
}
SIYWall >> blockTexture [

	^ '/SIYWall.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 1/2/2024 13:00'
}
SIYWall >> nounTexture [

	^ '/SIYWallT.png'
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'LK 2/4/2024 15:08'
}
SIYWall >> symbol [

	^ #wall
]
