Class {
	#name : #SIYLake07,
	#superclass : #SIYWorld2,
	#category : #'SIY-Levels'
}

{
	#category : #'level design',
	#'squeak_changestamp' : 'LK 1/9/2024 15:41'
}
SIYLake07 >> arenaExtent [

	^ 24@14
]

{
	#category : #'level design',
	#'squeak_changestamp' : 'LK 1/9/2024 16:08'
}
SIYLake07 >> buildLevel [
	
"work in progress"
]

{
	#category : #'level design',
	#'squeak_changestamp' : 'LK 1/9/2024 15:41'
}
SIYLake07 >> description [

	^ 'Level 2.7: Locked In'
]

{
	#category : #'level design',
	#'squeak_changestamp' : 'LK 1/9/2024 15:42'
}
SIYLake07 >> nextLevel [

	^ SIYLake08
]

{
	#category : #'level design',
	#'squeak_changestamp' : 'LK 1/9/2024 15:42'
}
SIYLake07 >> previousLevel [

	^ SIYLake06
]
